version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "nuget"
    versioning-strategy: increase
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10